### ISSUE TITLE
Castle-Model-Viewer 5.2.0 -> 5.3.0: Some Fill Modes behave differently

### ISSUE THREAD

**Issue by elmkni** [castle-engine/castle-model-viewer#101]
Hi Michalis,

it's me, Elmar, again...

I've just tested the newest snapshot of [Castle-Model-Viewer 5.3.0](https://github.com/castle-engine/castle-model-viewer/releases/download/snapshot/castle-model-viewer-5.3.0-win64-x86_64.zip) (2024-09-01) and found following
diffrences in the behavior of some of the fill modes (compared to version [5.2.0)](https://github.com/castle-engine/castle-model-viewer/releases/download/v5.2.0/castle-model-viewer-5.2.0-win64-x86_64.zip) (2024-08-28):

![Compare50](https://github.com/user-attachments/assets/0c89d680-9427-418e-9664-062d5646887c)

It seems that 
  
Fill Mode: Solid Shape
Fill Mode: Solid Wireframe (Single Color)
Fill Mode: Normal with Silhouette (Single Color)

behave in an odd way ...

Please help!

with best regards

Elmar

My test files: [view3dscene_issue_101.zip](https://github.com/user-attachments/files/16840807/view3dscene_issue_101.zip)

**Comment by michaliskambi** [comment]
Fixed, thank you!

Indeed, this was a temporary regression. Give our GitHub Actions a few hours to update everything and the new snapshots will be good :)

**Comment by michaliskambi** [comment]
>  Give our GitHub Actions a few hours to update everything and the new snapshots will be good :)

It took more time that "a few hours" this time (due to unrelated issues caused by my CGE changes over the last weekend) but it's done. The latest snapshots of Castle Model Viewer should have this fixed.
