### ISSUE TITLE
Inline description field

### ISSUE THREAD

**Issue by brutzman** [castle-engine/castle-model-viewer#103]
Inline supports the description field in X3D 4.0.

* X3D 4.0 Architecture, 9 Networking component, 9.4.2 Inline
* https://www.web3d.org/specifications/X3Dv4/ISO-IEC19775-1v4-IS/Part01/components/networking.html#Inline

Test case:
* https://www.web3d.org/x3d/content/examples/Basic/X3dSpecifications/InlineImport.x3d
* castle-model-converter: Warning: X3D: Unknown X3D field name (unhandled X3D XML attribute) "description" in node "Inline"

There are a number of additional nodes that had description field added in X3D 4.0.  A comprehensive list can be found at
* https://www.web3d.org/specifications/AllX3dElementsAttributes4.0.xml
* https://www.web3d.org/specifications/AllX3dElementsAttributes4.0.txt
* https://www.web3d.org/specifications/X3dUnifiedObjectModel-4.0.xml

**Comment by michaliskambi** [comment]
Thank you, added `description` and a few more missing stuff from `Inline`!
