### ISSUE TITLE
Probably a very easy issue with my data file, but the validator/error message isn't helping much

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/castle-model-viewer#94]
$ ~/Downloads/castle-model-viewer-4.3.0-win64-x86_64/castle-model-viewer/castle-model-converter.exe --validate JinSkip09x.x3d 2>&1
castle-model-converter: Warning: X3D: Error when reading MFString field "value" value. Possibly missing double quotes (treating as a single string): Error at line 1 column 2: Illegal character in stream : ' (#39)

{ ignoring the standard joints message for now ]

Here's the file:
[JinSkip09x.x3d.txt](https://github.com/castle-engine/castle-model-viewer/files/15284931/JinSkip09x.x3d.txt)

Probably Joe W. has already reported this.

Thanks, I will try downloading the latest viewer

**Comment by coderextreme** [comment]
Here's the offending line:


<MetadataString name='gender' value="'female'"/>

Closing

**Comment by coderextreme** [comment]
Note that this was nowhere near line 1.  That might be able to be fixed.

**Comment by michaliskambi** [comment]
I see it's closed. For others, to make it clear, the solution is to do

```
<MetadataString name='gender' value='"female"'/>
```

i.e. `value = <apostrophe> <double-quote> female <double-quote><apostrophe>` . This is valid X3D XML, with MFString. 

Doing `value = <double-quote> <apostrophe> female <apostrophe> <double-quote>` is not valid.

> Note that this was nowhere near line 1. That might be able to be fixed.

Indeed. That error message talks about 1st line of MFString contents -- which will be almost always 1... I agree it is confusing. I'll look to improve this, thanks!
