### ISSUE TITLE
Previously mentioned issue.  glTF conversion with same node name warning

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/castle-model-viewer#96]
$ ~/Downloads/castle-model-viewer-4.3.0-win64-x86_64/castle-model-viewer/castle-model-converter.exe --encoding=xml gramps_animated_full_1.gltf > gramps_animated_full_1.gltf.x3d
castle-model-converter: Warning: Node name "gramps_low_poly" used multiple times for different nodes (Transform and Group). This is not allowed in X3D.
  Common reasons:
  1. You imported glTF model with non-unique names. While this is valid in glTF, we recommend to prepare glTF models with unique names for everything.
  2. You have a VRML model with non-unique names. While this is valid in VRML, we recommend to upgrade all VRML models to X3D and make names unique.
  
glTF attached.  I am trying conversions from glb/glTF to .x3d but it's taking ages.

[gramps_animated_full_1.gltf.txt](https://github.com/castle-engine/castle-model-viewer/files/15360436/gramps_animated_full_1.gltf.txt)

**Comment by michaliskambi** [comment]
> [gramps_animated_full_1.gltf.txt](https://github.com/castle-engine/castle-model-viewer/files/15360436/gramps_animated_full_1.gltf.txt)

You didn't attach the associated `gramps_animated_full_1.bin`, so I cannot easily test it (`castle-model-converter gramps_animated_full_1.gltf new.x3d` says that is cannot find `gramps_animated_full_1.bin`).

That being said, I did fix this issue yesterday. I'm right now in the process of making a news about it (and related stuff) on CGE news, on https://castle-engine.io/wp/ .

We now rename non-unique node names from glTF to X3D. So valid glTF -> should result in valid X3D, as we make names unique, without warnings. This is documented now on https://castle-engine.io/gltf#unique_names and even more details in https://github.com/castle-engine/castle-engine/blob/master/doc/miscellaneous_notes/renaming_nodes_at_import.md .

**Comment by michaliskambi** [comment]
A news post documenting the change will be public later today (look for post titled _"Models can be saved to X3D or STL now (soon to glTF too), new engine API to register custom model formats that can be loaded/saved, proper handling of duplicate node names in glTF on conversion to X3D"_ in ~9 hours on https://castle-engine.io/wp/ .

Here's a snippet relevant to new node names strategy:

"""
_Finally, we also changed our strategy to deal with name duplicates on input (like non-unique names in glTF content). We now rename non-unique node names on input (like glTF) to be unique on output (to guarantee to make valid X3D from valid input glTF)._

_The result is that valid glTF on input (which means: with possible non-unique names for glTF stuff) should always result in valid X3D on output (which means: X3D node names have to be unique)._

_See <a href="https://castle-engine.io/gltf#unique_names">docs: glTF files may have non-unique names, but we advise to generate them to be unique; eventually we'll force them unique at loading</a>. See also more details in the <a href="https://github.com/castle-engine/castle-engine/blob/master/doc/miscellaneous_notes/renaming_nodes_at_import.md">What to do with node names when importing e.g. glTF?</a> document._

_And see demo of glTF including in X3D: <a href="https://github.com/michaliskambi/x3d-tests/tree/master/gltf/avocado_and_exports">avocado_and_exports</a>. Here the <a href="https://castle-engine.io/castle-model-viewer">Castle Model Viewer</a> allows to work with the glTF file, despite glTF having duplicate names._
"""

**Comment by coderextreme** [comment]
Hmm. I didn't realize that .bins could get attached to issues?   Perhaps a
.zip?

Thanks!

John

**Comment by michaliskambi** [comment]
> Hmm. I didn't realize that .bins could get attached to issues?   Perhaps a .zip?

Indeed, practically I recommend to just zip the model (.gltf + .bin + any textures) and attach zip to GitHub bugreports.
